#!/bin/bash

# Get the Real Username
RUID=$(who | awk 'FNR == 1 {print $1}')

# Translate Real Username to Real User ID
RUSER_UID=$(id -u ${RUID})

# Set env for the Real User
touch /home/${RUID}/.zshrc
if [[ -f "/home/${RUID}/.zshrc" ]] ; then
    echo "source /usr/share/powerlevel9k/powerlevel9k.zsh-theme" >> "/home/${RUID}/.zshrc"
    sudo chown ${RUID}:${RUID} /home/${RUID}/.zshrc
fi

# 단축키를 자동으로 추가하는 기능
function addKeyboardShortcut() {

    IFS=', ' read -r -a array <<< `sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings get org.cinnamon.desktop.keybindings custom-list | tr -d '[' | tr -d ']'`

    # echo "the number of elements in an array : ${#array[@]}"
    # echo "the value of elements in an array : ${array[-1]}"
    # echo "last index value : ${array[@]: -1:1}"
    # echo "index number: ${!array[@]}"

    if [[ "${array[-1]}" = "@as" ]] ; then
        result="'custom0'"        
        result="[${result}]"        

        sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings set org.cinnamon.desktop.keybindings custom-list "${result}"

        # Set gsettings for the Real User
        sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ binding "['<Primary><Alt>z']"
        sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ command 'gnome-terminal -e /usr/bin/zsh'
        sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ name 'ZSH'        
    else
        # Add new element at the end of the array
        array=(${array[@]} "'custom${#array[@]}'")
        CUSTOM_KEY=`echo ${array[@]: -1:1} | tr -d "'"`
        # echo ${CUSTOM_KEY}

        # array join
        function join { local IFS="$1"; shift; echo "$*"; }        
        result=$(join , ${array[@]})
        result="[${result}]"        

        sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings set org.cinnamon.desktop.keybindings custom-list "${result}"

        # Set gsettings for the Real User
        sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/${CUSTOM_KEY}/ binding "['<Primary><Alt>z']"
        sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/${CUSTOM_KEY}/ command 'gnome-terminal -e /usr/bin/zsh'
        sudo -u ${RUID} DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/${RUSER_UID}/bus" gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/${CUSTOM_KEY}/ name 'ZSH'        
    fi

    # echo $result

}

addKeyboardShortcut

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
        if which update-icon-caches >/dev/null 2>&1 ; then
                update-icon-caches /usr/share/icons
        fi
fi

#Print Message if running under GUI
xcheck=`tty | cut -d '/' -f3`
if [[ $xcheck = "pts" ]]
then
    echo $(zenity --info --width=300 --height=180 --title="사용안내" --text "<b>ZSH 프로그램 설치가 완료되었습니다.</b>\n\n단축키 <b><span color=\"blue\">CTRL+ALT+Z</span></b> 로 프로그램을 실행할수 있습니다.\n\n기본 단축키를 변경하려면 키보드 설정에서 단축키 탭을 이용하세요.\n\n<a href=\"https://hamonikr.org\">https://hamonikr.org</a>") 2> /dev/null
else
    echo "ZSH 프로그램 설치가 완료되었습니다.

단축키 CTRL+ALT+Z로 프로그램을 실행할수 있습니다.

기본 단축키를 변경하려면 키보드 설정에서 단축키 탭을 이용하세요.

https://hamonikr.org"

fi

#DEBHELPER#
exit 0
