name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-ubuntu-2404:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build Debian Package
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: ubuntu:24.04
          buildpackage-opts: -us -uc
          before-build-hook: apt-get install -y devscripts equivs && mk-build-deps --install --remove debian/control && debchange --controlmaint --local="+ci${{ github.run_id }}~ubuntu2404~git$(git rev-parse --short HEAD)" "CI build"
          extra-build-deps: devscripts git equivs debhelper build-essential
          host-arch: amd64
          artifacts-dir: debian/artifacts-ubuntu2404

      - name: Upload Debian Package
        uses: actions/upload-artifact@v2
        with:
          name: debian-package-ubuntu2404
          path: debian/artifacts-ubuntu2404/*.deb

  build-ubuntu-2204:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build Debian Package
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: ubuntu:22.04
          buildpackage-opts: -us -uc
          before-build-hook: apt-get install -y devscripts equivs && mk-build-deps --install --remove debian/control && debchange --controlmaint --local="+ci${{ github.run_id }}~ubuntu2204~git$(git rev-parse --short HEAD)" "CI build"
          extra-build-deps: devscripts git equivs debhelper build-essential
          host-arch: amd64
          artifacts-dir: debian/artifacts-ubuntu2204

      - name: Upload Debian Package
        uses: actions/upload-artifact@v2
        with:
          name: debian-package-ubuntu2204
          path: debian/artifacts-ubuntu2204/*.deb

  release:
    needs: [build-ubuntu-2404, build-ubuntu-2204]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Download build artifacts for Ubuntu 24.04
        uses: actions/download-artifact@v2
        with:
          name: debian-package-ubuntu2404
          path: .

      - name: Download build artifacts for Ubuntu 22.04
        uses: actions/download-artifact@v2
        with:
          name: debian-package-ubuntu2204
          path: .

      - run: ls -R .

      - name: Set latest and previous tags
        id: tags
        run: |
          latest_tag=$(git describe --tags --abbrev=0 --match "v*")
          if [ -z "$latest_tag" ]; then
            latest_tag=$(git rev-list --max-parents=0 HEAD)
            previous_tag=$latest_tag
          else
            previous_tag=$(git tag --sort=-creatordate | grep -E "^v" | grep -B 1 $latest_tag | head -n 1)
            if [ "$latest_tag" = "$previous_tag" ]; then
              previous_tag=$(git rev-list --max-parents=0 HEAD)
            fi
          fi
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
          echo "previous_tag=$previous_tag" >> $GITHUB_ENV

      - name: Generate Changelog
        id: changelog
        env:
          REPO_URL: "https://github.com/${{ github.repository }}"
        run: |
          echo "## Changelog :" > changelog.txt
          git log --pretty=format:"- %ad %an: %s ([%h](${REPO_URL}/commit/%H))" --date=short ${{ env.previous_tag }}..${{ env.latest_tag }} --no-merges >> changelog.txt

      - run: cat changelog.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./*.deb
          body_path: ./changelog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
